version: '3'

services:
    mongo:
        container_name: persistent_mongo
        image: mongo:latest
        volumes:
            - ./data/mongo:/data/db
        user: "${UID_GID}"
        ports:
            - "27017:27017"
        networks:
            - common
        restart: always

    redis:
        container_name: persistent_redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
        user: "${UID_GID}"
        ports:
            - "6379:6379"
        networks:
            - common
        restart: always

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        container_name: persistent_elasticsearch
        environment:
            # single node for develop
            -  discovery.type=single-node

            # must set vm.max_map_count least 262144 in production
            # - cluster.name=docker-cluster
            # - bootstrap.memory_lock=true
            # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./data/elasticsearch:/usr/share/elasticsearch/data
        user: "${UID_GID}"
        ports:
            - 9200:9200
        networks:
            - common

    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        container_name: persistent_kibana
        ports:
            - 5601:5601
        networks:
            - common

networks:
    common: